#!/bin/sh
# Script is meant for getting Red Hat based systems up and running

# Enable EPEL Repository
sudo dnf install epel-release -y
sudo dnf config-manager --set-enabled powertools  # For some packages in EPEL that depend on PowerTools

# Update system
sudo dnf update -y && sudo dnf upgrade -y

# Install extra packages needed for system
sudo dnf install -y zsh vim openssh-server htop wireshark tmux python3 zip btop fzf tldr neofetch git util-linux-user nmap traceroute


# Ensure openssh-server (sshd) is enabled and running
sudo systemctl enable sshd
sudo systemctl start sshd

# Install Docker and Docker Compose
sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
sudo dnf install -y docker-ce docker-ce-cli containerd.io
sudo systemctl start docker && sudo systemctl enable docker
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# Add the current user to the Docker group
sudo usermod -aG docker $USER

# Pull Vim settings and apply to both user and root, with backup for existing .vimrc
git clone https://github.com/xkyuz/vimfiles.git ~/vimfiles
mv ~/.vimrc ~/.vimrc.backup 2> /dev/null
cp ~/vimfiles/vimrc ~/.vimrc
mv -v vimfiles/vim ~/.vim
sudo mv /root/.vimrc /root/.vimrc.backup 2> /dev/null
sudo cp ~/vimfiles/vimrc /root/.vimrc
sudo mv -v vimfiles/vim /root/.vim
rm -rf ~/vimfiles

# Install Oh My Zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# enable zsh as default
chsh -s $(which zsh)

# Configure tmux to enable mouse support
echo "set -g mouse on" >> ~/.tmux.conf



