#!/bin/sh
# Script is meant for getting Red Hat based systems up and running

# Enable EPEL Repository
sudo dnf install epel-release -y
sudo dnf config-manager --set-enabled powertools  # For some packages in EPEL that depend on PowerTools

# Update system
sudo dnf update -y && sudo dnf upgrade -y

# add aliases to bash and zsh 
echo "alias uupdate='sudo dnf update -y && sudo dnf upgrade -y'" >> ~/.bashrc
echo "alias uupdate='sudo dnf update -y && sudo dnf upgrade -y'" >> ~/.zshrc


# Install extra packages needed for system
sudo dnf install -y zsh vim openssh-server htop wireshark tmux python3 zip btop fzf tldr neofetch git util-linux-user nmap traceroute


# Ensure openssh-server (sshd) is enabled and running
sudo systemctl enable sshd
sudo systemctl start sshd

# Install Docker and Docker Compose
sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
sudo dnf -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
sudo systemctl --now enable docker

# Add the current user to the Docker group
sudo usermod -aG docker $(whoami)

# Pull Vim settings and apply to both user and root, with backup for existing .vimrc
git clone https://github.com/xkyuz/vimfiles.git ~/vimfiles
mv ~/.vimrc ~/.vimrc.backup 2> /dev/null
cp ~/vimfiles/vimrc ~/.vimrc
mv -v vimfiles/vim ~/.vim
sudo mv /root/.vimrc /root/.vimrc.backup 2> /dev/null
sudo cp ~/vimfiles/vimrc /root/.vimrc
sudo mv -v vimfiles/vim /root/.vim
rm -rf ~/vimfiles

# Install Oh My Zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

## Download
wget https://raw.githubusercontent.com/xkyuz/newlinuxinstaller/master/mela.zsh-theme
wget --output-document zshrc https://raw.githubusercontent.com/xkyuz/newlinuxinstaller/master/.zshrc

# Copy mela.zsh-theme to .oh-my-zsh/themes/ folder
mv mela.zsh-theme ~/.oh-my-zsh/themes/
# Replace the current .zshrc with the one from the repository
mv .zshrc ~/.zshrc

# Configure tmux to enable mouse support
echo "set -g mouse on" >> ~/.tmux.conf

# enable zsh as default
chsh -s $(which zsh)


